dist: xenial

language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGOVER=django19
  - DJANGOVER=django110
  - DJANGOVER=django111
  - DJANGOVER=django20
  - DJANGOVER=django21
  - DJANGOVER=django22

matrix:
  exclude:
    - python: 2.7
      env: DJANGOVER=django20
    - python: 2.7
      env: DJANGOVER=django21
    - python: 2.7
      env: DJANGOVER=django22
    - python: 3.7
      env: DJANGOVER=django19
    - python: 3.7
      env: DJANGOVER=django110

install:
  - pip install tox

script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DJANGOVER ]]; then export TOX_ENV=py27-$DJANGOVER; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $DJANGOVER ]]; then export TOX_ENV=py35-$DJANGOVER; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' && $DJANGOVER ]]; then export TOX_ENV=py36-$DJANGOVER; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' && $DJANGOVER ]]; then export TOX_ENV=py37-$DJANGOVER; fi"
  - tox -r -e "$TOX_ENV"
